[build]
    command = 'mv "$PWD" "${PWD%/*}/hugo-vanilla-theme" && hugo -s exampleSite --themesDir ../..'
    publish = "exampleSite/public"

[build.environment]
    HUGO_VERSION = "0.73.0"
    HUGO_ENV = "production"
